### ISSUE TITLE
firmware upgrade fails with error

### ISSUE THREAD

**Issue by briankearney** [McIndi/mast#43]
#### _Issue template for MAST for IBM DataPower_

_Please give a brief description of the issue you are having_
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\mast\plugin_utils\plugin_functions.py", line 470, in _call_method
    out, hist = func(**kwargs)
  File "build\bdist.win-amd64\egg\mast\datapower\system\system.py", line 2097, in firmware_upgrade
    web)
  File "build\bdist.win-amd64\egg\mast\datapower\system\system.py", line 3533, in clean_up
    check_hostname=check_hostname)
  File "build\bdist.win-amd64\egg\mast\datapower\datapower\environment.py", line 73, in __init__
    self.initialize()
  File "build\bdist.win-amd64\egg\mast\datapower\datapower\environment.py", line 106, in initialize
    appliance.request.set_timeout(self.timeout)
  File "build\bdist.win-amd64\egg\mast\datapower\datapower\WSClientLib.py", line 241, in set_timeout
    self._timeout = int(timeout)
ValueError: invalid literal for int() with base 10: 'default'

_Please answer each question as best as you can_

1. **What were you trying to do?** firmware upgrade
2. **What were you expecting to happen?** normal firmware upgrade to occur
3. **What were the actual results?** error message
4. **Was this a fresh install of MAST or when was the last time you installed a hotfix?** 2.1.1 hotfix was installed 2 days ago
5. **Please provide any output from the command (If in the web gui click the `history` link in the output and paste that).**
    Sorry, an unhandled exception occurred while performing action:
	 invalid literal for int() with base 10: 'default'

Thank you for taking the time to submit an issue, this is the only way we can continue to improve MAST in response to our customers needs.

**Comment by iLoveTux** [comment]
This should be fixed in commit #cb71dcc4e2b8f5010f15ae17486584477908e2f1,

I will leave this open for a time while the changes are tested before I close the issue
